#v.1.4.1
[pxccluster]
activeFailover = 1
failBack = false
checkTimeOut = 2000
# debug = 1 //Deprecated: this is redundant and not in use
mainSegment = 0
sslClient = "client-cert.pem"
sslKey = "client-key.pem"
sslCa = "ca.pem"
sslCertificatePath = "/opt/cert/ssl_test"
hgW = 100
hgR = 101
configHgRange =8000
maintenanceHgRange =9000
bckHgW = 8100 #deprecated
bckHgR = 8101 #deprecated
singlePrimary = true
maxNumWriters = 1
writerIsAlsoReader = 1
retryUp = 0
retryDown = 2
clusterId = 10
persistPrimarySettings=0 #0 disable| 1 only persist Write settings | 2 persist Reand and Write settings

[proxysql]
port = 6032
host = "127.0.0.1"
user = "<valid user to connect from real ip as for proxysql_server table>"
password = "<password>"
clustered = false
lockfilepath ="/var/run/pxc_scheduler_handler"
respectManualOfflineSoft=false

[global]
logLevel = "info"
logTarget = "stdout" #stdout | file
logFile = "/var/log/pxc_scheduler_handler/pscheduler.log"
daemonize = false
daemonInterval = 2000
performance = true
OS = "na"
lockfiletimeout = 60 #seconds
lockclustertimeout = 600 #120 # seconds
